[package]
name = "http_server_2"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0.145"
tower-http = { version = "0.6.6", features = ["cors"] }
tower = "0.5.2"
http = "1.3.1"